"""Constants."""
import numpy as np
import random

WI_STATUS = ["COMPLETE", "PENDING", "BLOCKED"]
US_STATE_ABB_MAP = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC"
}
US_CITIES_MAP = {
    "New York": [
        "New York",
        "Buffalo",
        "Rochester",
        "Yonkers",
        "Syracuse",
        "Albany",
        "New Rochelle",
        "Mount Vernon",
        "Schenectady",
        "Utica",
        "White Plains",
        "Hempstead",
        "Troy",
        "Niagara Falls",
        "Binghamton",
        "Freeport",
        "Valley Stream",
    ],
    "California": [
        "Los Angeles",
        "San Diego",
        "San Jose",
        "San Francisco",
        "Fresno",
        "Sacramento",
        "Long Beach",
        "Oakland",
        "Bakersfield",
        "Anaheim",
        "Santa Ana",
        "Riverside",
        "Stockton",
        "Chula Vista",
        "Irvine",
        "Fremont",
        "San Bernardino",
        "Modesto",
        "Fontana",
        "Oxnard",
        "Moreno Valley",
        "Huntington Beach",
        "Glendale",
        "Santa Clarita",
        "Garden Grove",
        "Oceanside",
        "Rancho Cucamonga",
        "Santa Rosa",
        "Ontario",
        "Lancaster",
        "Elk Grove",
        "Corona",
        "Palmdale",
        "Salinas",
        "Pomona",
        "Hayward",
        "Escondido",
        "Torrance",
        "Sunnyvale",
        "Orange",
        "Fullerton",
        "Pasadena",
        "Thousand Oaks",
        "Visalia",
        "Simi Valley",
        "Concord",
        "Roseville",
        "Victorville",
        "Santa Clara",
        "Vallejo",
        "Berkeley",
        "El Monte",
        "Downey",
        "Costa Mesa",
        "Inglewood",
        "Carlsbad",
        "San Buenaventura (Ventura)",
        "Fairfield",
        "West Covina",
        "Murrieta",
        "Richmond",
        "Norwalk",
        "Antioch",
        "Temecula",
        "Burbank",
        "Daly City",
        "Rialto",
        "Santa Maria",
        "El Cajon",
        "San Mateo",
        "Clovis",
        "Compton",
        "Jurupa Valley",
        "Vista",
        "South Gate",
        "Mission Viejo",
        "Vacaville",
        "Carson",
        "Hesperia",
        "Santa Monica",
        "Westminster",
        "Redding",
        "Santa Barbara",
        "Chico",
        "Newport Beach",
        "San Leandro",
        "San Marcos",
        "Whittier",
        "Hawthorne",
        "Citrus Heights",
        "Tracy",
        "Alhambra",
        "Livermore",
        "Buena Park",
        "Menifee",
        "Hemet",
        "Lakewood",
        "Merced",
        "Chino",
        "Indio",
        "Redwood City",
        "Lake Forest",
        "Napa",
        "Tustin",
        "Bellflower",
        "Mountain View",
        "Chino Hills",
        "Baldwin Park",
        "Alameda",
        "Upland",
        "San Ramon",
        "Folsom",
        "Pleasanton",
        "Union City",
        "Perris",
        "Manteca",
        "Lynwood",
        "Apple Valley",
        "Redlands",
        "Turlock",
        "Milpitas",
        "Redondo Beach",
        "Rancho Cordova",
        "Yorba Linda",
        "Palo Alto",
        "Davis",
        "Camarillo",
        "Walnut Creek",
        "Pittsburg",
        "South San Francisco",
        "Yuba City",
        "San Clemente",
        "Laguna Niguel",
        "Pico Rivera",
        "Montebello",
        "Lodi",
        "Madera",
        "Santa Cruz",
        "La Habra",
        "Encinitas",
        "Monterey Park",
        "Tulare",
        "Cupertino",
        "Gardena",
        "National City",
        "Rocklin",
        "Petaluma",
        "Huntington Park",
        "San Rafael",
        "La Mesa",
        "Arcadia",
        "Fountain Valley",
        "Diamond Bar",
        "Woodland",
        "Santee",
        "Lake Elsinore",
        "Porterville",
        "Paramount",
        "Eastvale",
        "Rosemead",
        "Hanford",
        "Highland",
        "Brentwood",
        "Novato",
        "Colton",
        "Cathedral City",
        "Delano",
        "Yucaipa",
        "Watsonville",
        "Placentia",
        "Glendora",
        "Gilroy",
        "Palm Desert",
        "Cerritos",
        "West Sacramento",
        "Aliso Viejo",
        "Poway",
        "La Mirada",
        "Rancho Santa Margarita",
        "Cypress",
        "Dublin",
        "Covina",
        "Azusa",
        "Palm Springs",
        "San Luis Obispo",
        "Ceres",
        "San Jacinto",
        "Lincoln",
        "Newark",
        "Lompoc",
        "El Centro",
        "Danville",
        "Bell Gardens",
        "Coachella",
        "Rancho Palos Verdes",
        "San Bruno",
        "Rohnert Park",
        "Brea",
        "La Puente",
        "Campbell",
        "San Gabriel",
        "Beaumont",
        "Morgan Hill",
        "Culver City",
        "Calexico",
        "Stanton",
        "La Quinta",
        "Pacifica",
        "Montclair",
        "Oakley",
        "Monrovia",
        "Los Banos",
        "Martinez",
    ],
    "Illinois": [
        "Chicago",
        "Aurora",
        "Rockford",
        "Joliet",
        "Naperville",
        "Springfield",
        "Peoria",
        "Elgin",
        "Waukegan",
        "Cicero",
        "Champaign",
        "Bloomington",
        "Arlington Heights",
        "Evanston",
        "Decatur",
        "Schaumburg",
        "Bolingbrook",
        "Palatine",
        "Skokie",
        "Des Plaines",
        "Orland Park",
        "Tinley Park",
        "Oak Lawn",
        "Berwyn",
        "Mount Prospect",
        "Normal",
        "Wheaton",
        "Hoffman Estates",
        "Oak Park",
        "Downers Grove",
        "Elmhurst",
        "Glenview",
        "DeKalb",
        "Lombard",
        "Belleville",
        "Moline",
        "Buffalo Grove",
        "Bartlett",
        "Urbana",
        "Quincy",
        "Crystal Lake",
        "Plainfield",
        "Streamwood",
        "Carol Stream",
        "Romeoville",
        "Rock Island",
        "Hanover Park",
        "Carpentersville",
        "Wheeling",
        "Park Ridge",
        "Addison",
        "Calumet City",
    ],
    "Texas": [
        "Houston",
        "San Antonio",
        "Dallas",
        "Austin",
        "Fort Worth",
        "El Paso",
        "Arlington",
        "Corpus Christi",
        "Plano",
        "Laredo",
        "Lubbock",
        "Garland",
        "Irving",
        "Amarillo",
        "Grand Prairie",
        "Brownsville",
        "Pasadena",
        "McKinney",
        "Mesquite",
        "McAllen",
        "Killeen",
        "Frisco",
        "Waco",
        "Carrollton",
        "Denton",
        "Midland",
        "Abilene",
        "Beaumont",
        "Round Rock",
        "Odessa",
        "Wichita Falls",
        "Richardson",
        "Lewisville",
        "Tyler",
        "College Station",
        "Pearland",
        "San Angelo",
        "Allen",
        "League City",
        "Sugar Land",
        "Longview",
        "Edinburg",
        "Mission",
        "Bryan",
        "Baytown",
        "Pharr",
        "Temple",
        "Missouri City",
        "Flower Mound",
        "Harlingen",
        "North Richland Hills",
        "Victoria",
        "Conroe",
        "New Braunfels",
        "Mansfield",
        "Cedar Park",
        "Rowlett",
        "Port Arthur",
        "Euless",
        "Georgetown",
        "Pflugerville",
        "DeSoto",
        "San Marcos",
        "Grapevine",
        "Bedford",
        "Galveston",
        "Cedar Hill",
        "Texas City",
        "Wylie",
        "Haltom City",
        "Keller",
        "Coppell",
        "Rockwall",
        "Huntsville",
        "Duncanville",
        "Sherman",
        "The Colony",
        "Burleson",
        "Hurst",
        "Lancaster",
        "Texarkana",
        "Friendswood",
        "Weslaco",
    ],
    "Pennsylvania": [
        "Philadelphia",
        "Pittsburgh",
        "Allentown",
        "Erie",
        "Reading",
        "Scranton",
        "Bethlehem",
        "Lancaster",
        "Harrisburg",
        "Altoona",
        "York",
        "State College",
        "Wilkes-Barre",
    ],
    "Arizona": [
        "Phoenix",
        "Tucson",
        "Mesa",
        "Chandler",
        "Glendale",
        "Scottsdale",
        "Gilbert",
        "Tempe",
        "Peoria",
        "Surprise",
        "Yuma",
        "Avondale",
        "Goodyear",
        "Flagstaff",
        "Buckeye",
        "Lake Havasu City",
        "Casa Grande",
        "Sierra Vista",
        "Maricopa",
        "Oro Valley",
        "Prescott",
        "Bullhead City",
        "Prescott Valley",
        "Marana",
        "Apache Junction",
    ],
    "Florida": [
        "Jacksonville",
        "Miami",
        "Tampa",
        "Orlando",
        "St. Petersburg",
        "Hialeah",
        "Tallahassee",
        "Fort Lauderdale",
        "Port St. Lucie",
        "Cape Coral",
        "Pembroke Pines",
        "Hollywood",
        "Miramar",
        "Gainesville",
        "Coral Springs",
        "Miami Gardens",
        "Clearwater",
        "Palm Bay",
        "Pompano Beach",
        "West Palm Beach",
        "Lakeland",
        "Davie",
        "Miami Beach",
        "Sunrise",
        "Plantation",
        "Boca Raton",
        "Deltona",
        "Largo",
        "Deerfield Beach",
        "Palm Coast",
        "Melbourne",
        "Boynton Beach",
        "Lauderhill",
        "Weston",
        "Fort Myers",
        "Kissimmee",
        "Homestead",
        "Tamarac",
        "Delray Beach",
        "Daytona Beach",
        "North Miami",
        "Wellington",
        "North Port",
        "Jupiter",
        "Ocala",
        "Port Orange",
        "Margate",
        "Coconut Creek",
        "Sanford",
        "Sarasota",
        "Pensacola",
        "Bradenton",
        "Palm Beach Gardens",
        "Pinellas Park",
        "Coral Gables",
        "Doral",
        "Bonita Springs",
        "Apopka",
        "Titusville",
        "North Miami Beach",
        "Oakland Park",
        "Fort Pierce",
        "North Lauderdale",
        "Cutler Bay",
        "Altamonte Springs",
        "St. Cloud",
        "Greenacres",
        "Ormond Beach",
        "Ocoee",
        "Hallandale Beach",
        "Winter Garden",
        "Aventura",
    ],
    "Indiana": [
        "Indianapolis",
        "Fort Wayne",
        "Evansville",
        "South Bend",
        "Carmel",
        "Bloomington",
        "Fishers",
        "Hammond",
        "Gary",
        "Muncie",
        "Lafayette",
        "Terre Haute",
        "Kokomo",
        "Anderson",
        "Noblesville",
        "Greenwood",
        "Elkhart",
        "Mishawaka",
        "Lawrence",
        "Jeffersonville",
        "Columbus",
        "Portage",
    ],
    "Ohio": [
        "Columbus",
        "Cleveland",
        "Cincinnati",
        "Toledo",
        "Akron",
        "Dayton",
        "Parma",
        "Canton",
        "Youngstown",
        "Lorain",
        "Hamilton",
        "Springfield",
        "Kettering",
        "Elyria",
        "Lakewood",
        "Cuyahoga Falls",
        "Middletown",
        "Euclid",
        "Newark",
        "Mansfield",
        "Mentor",
        "Beavercreek",
        "Cleveland Heights",
        "Strongsville",
        "Dublin",
        "Fairfield",
        "Findlay",
        "Warren",
        "Lancaster",
        "Lima",
        "Huber Heights",
        "Westerville",
        "Marion",
        "Grove City",
    ],
    "North Carolina": [
        "Charlotte",
        "Raleigh",
        "Greensboro",
        "Durham",
        "Winston-Salem",
        "Fayetteville",
        "Cary",
        "Wilmington",
        "High Point",
        "Greenville",
        "Asheville",
        "Concord",
        "Gastonia",
        "Jacksonville",
        "Chapel Hill",
        "Rocky Mount",
        "Burlington",
        "Wilson",
        "Huntersville",
        "Kannapolis",
        "Apex",
        "Hickory",
        "Goldsboro",
    ],
    "Michigan": [
        "Detroit",
        "Grand Rapids",
        "Warren",
        "Sterling Heights",
        "Ann Arbor",
        "Lansing",
        "Flint",
        "Dearborn",
        "Livonia",
        "Westland",
        "Troy",
        "Farmington Hills",
        "Kalamazoo",
        "Wyoming",
        "Southfield",
        "Rochester Hills",
        "Taylor",
        "Pontiac",
        "St. Clair Shores",
        "Royal Oak",
        "Novi",
        "Dearborn Heights",
        "Battle Creek",
        "Saginaw",
        "Kentwood",
        "East Lansing",
        "Roseville",
        "Portage",
        "Midland",
        "Lincoln Park",
        "Muskegon",
    ],
    "Tennessee": [
        "Memphis",
        "Nashville-Davidson",
        "Knoxville",
        "Chattanooga",
        "Clarksville",
        "Murfreesboro",
        "Jackson",
        "Franklin",
        "Johnson City",
        "Bartlett",
        "Hendersonville",
        "Kingsport",
        "Collierville",
        "Cleveland",
        "Smyrna",
        "Germantown",
        "Brentwood",
    ],
    "Massachusetts": [
        "Boston",
        "Worcester",
        "Springfield",
        "Lowell",
        "Cambridge",
        "New Bedford",
        "Brockton",
        "Quincy",
        "Lynn",
        "Fall River",
        "Newton",
        "Lawrence",
        "Somerville",
        "Waltham",
        "Haverhill",
        "Malden",
        "Medford",
        "Taunton",
        "Chicopee",
        "Weymouth Town",
        "Revere",
        "Peabody",
        "Methuen",
        "Barnstable Town",
        "Pittsfield",
        "Attleboro",
        "Everett",
        "Salem",
        "Westfield",
        "Leominster",
        "Fitchburg",
        "Beverly",
        "Holyoke",
        "Marlborough",
        "Woburn",
        "Chelsea",
    ],
    "Washington": [
        "Seattle",
        "Spokane",
        "Tacoma",
        "Vancouver",
        "Bellevue",
        "Kent",
        "Everett",
        "Renton",
        "Yakima",
        "Federal Way",
        "Spokane Valley",
        "Bellingham",
        "Kennewick",
        "Auburn",
        "Pasco",
        "Marysville",
        "Lakewood",
        "Redmond",
        "Shoreline",
        "Richland",
        "Kirkland",
        "Burien",
        "Sammamish",
        "Olympia",
        "Lacey",
        "Edmonds",
        "Bremerton",
        "Puyallup",
    ],
    "Colorado": [
        "Denver",
        "Colorado Springs",
        "Aurora",
        "Fort Collins",
        "Lakewood",
        "Thornton",
        "Arvada",
        "Westminster",
        "Pueblo",
        "Centennial",
        "Boulder",
        "Greeley",
        "Longmont",
        "Loveland",
        "Grand Junction",
        "Broomfield",
        "Castle Rock",
        "Commerce City",
        "Parker",
        "Littleton",
        "Northglenn",
    ],
    "District of Columbia": ["Washington"],
    "Maryland": [
        "Baltimore",
        "Frederick",
        "Rockville",
        "Gaithersburg",
        "Bowie",
        "Hagerstown",
        "Annapolis",
    ],
    "Kentucky": [
        "Louisville/Jefferson County",
        "Lexington-Fayette",
        "Bowling Green",
        "Owensboro",
        "Covington",
    ],
    "Oregon": [
        "Portland",
        "Eugene",
        "Salem",
        "Gresham",
        "Hillsboro",
        "Beaverton",
        "Bend",
        "Medford",
        "Springfield",
        "Corvallis",
        "Albany",
        "Tigard",
        "Lake Oswego",
        "Keizer",
    ],
    "Oklahoma": [
        "Oklahoma City",
        "Tulsa",
        "Norman",
        "Broken Arrow",
        "Lawton",
        "Edmond",
        "Moore",
        "Midwest City",
        "Enid",
        "Stillwater",
        "Muskogee",
    ],
    "Wisconsin": [
        "Milwaukee",
        "Madison",
        "Green Bay",
        "Kenosha",
        "Racine",
        "Appleton",
        "Waukesha",
        "Eau Claire",
        "Oshkosh",
        "Janesville",
        "West Allis",
        "La Crosse",
        "Sheboygan",
        "Wauwatosa",
        "Fond du Lac",
        "New Berlin",
        "Wausau",
        "Brookfield",
        "Greenfield",
        "Beloit",
    ],
    "Nevada": [
        "Las Vegas",
        "Henderson",
        "Reno",
        "North Las Vegas",
        "Sparks",
        "Carson City",
    ],
    "New Mexico": [
        "Albuquerque",
        "Las Cruces",
        "Rio Rancho",
        "Santa Fe",
        "Roswell",
        "Farmington",
        "Clovis",
    ],
    "Missouri": [
        "Kansas City",
        "St. Louis",
        "Springfield",
        "Independence",
        "Columbia",
        "Lee's Summit",
        "O'Fallon",
        "St. Joseph",
        "St. Charles",
        "St. Peters",
        "Blue Springs",
        "Florissant",
        "Joplin",
        "Chesterfield",
        "Jefferson City",
        "Cape Girardeau",
    ],
    "Virginia": [
        "Virginia Beach",
        "Norfolk",
        "Chesapeake",
        "Richmond",
        "Newport News",
        "Alexandria",
        "Hampton",
        "Roanoke",
        "Portsmouth",
        "Suffolk",
        "Lynchburg",
        "Harrisonburg",
        "Leesburg",
        "Charlottesville",
        "Danville",
        "Blacksburg",
        "Manassas",
    ],
    "Georgia": [
        "Atlanta",
        "Columbus",
        "Augusta-Richmond County",
        "Savannah",
        "Athens-Clarke County",
        "Sandy Springs",
        "Roswell",
        "Macon",
        "Johns Creek",
        "Albany",
        "Warner Robins",
        "Alpharetta",
        "Marietta",
        "Valdosta",
        "Smyrna",
        "Dunwoody",
    ],
    "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island"],
    "Minnesota": [
        "Minneapolis",
        "St. Paul",
        "Rochester",
        "Duluth",
        "Bloomington",
        "Brooklyn Park",
        "Plymouth",
        "St. Cloud",
        "Eagan",
        "Woodbury",
        "Maple Grove",
        "Eden Prairie",
        "Coon Rapids",
        "Burnsville",
        "Blaine",
        "Lakeville",
        "Minnetonka",
        "Apple Valley",
        "Edina",
        "St. Louis Park",
        "Mankato",
        "Maplewood",
        "Moorhead",
        "Shakopee",
    ],
    "Kansas": [
        "Wichita",
        "Overland Park",
        "Kansas City",
        "Olathe",
        "Topeka",
        "Lawrence",
        "Shawnee",
        "Manhattan",
        "Lenexa",
        "Salina",
        "Hutchinson",
    ],
    "Louisiana": [
        "New Orleans",
        "Baton Rouge",
        "Shreveport",
        "Lafayette",
        "Lake Charles",
        "Kenner",
        "Bossier City",
        "Monroe",
        "Alexandria",
    ],
    "Hawaii": ["Honolulu"],
    "Alaska": ["Anchorage"],
    "New Jersey": [
        "Newark",
        "Jersey City",
        "Paterson",
        "Elizabeth",
        "Clifton",
        "Trenton",
        "Camden",
        "Passaic",
        "Union City",
        "Bayonne",
        "East Orange",
        "Vineland",
        "New Brunswick",
        "Hoboken",
        "Perth Amboy",
        "West New York",
        "Plainfield",
        "Hackensack",
        "Sayreville",
        "Kearny",
        "Linden",
        "Atlantic City",
    ],
    "Idaho": [
        "Boise City",
        "Nampa",
        "Meridian",
        "Idaho Falls",
        "Pocatello",
        "Caldwell",
        "Coeur d'Alene",
        "Twin Falls",
    ],
    "Alabama": [
        "Birmingham",
        "Montgomery",
        "Mobile",
        "Huntsville",
        "Tuscaloosa",
        "Hoover",
        "Dothan",
        "Auburn",
        "Decatur",
        "Madison",
        "Florence",
        "Gadsden",
    ],
    "Iowa": [
        "Des Moines",
        "Cedar Rapids",
        "Davenport",
        "Sioux City",
        "Iowa City",
        "Waterloo",
        "Council Bluffs",
        "Ames",
        "West Des Moines",
        "Dubuque",
        "Ankeny",
        "Urbandale",
        "Cedar Falls",
    ],
    "Arkansas": [
        "Little Rock",
        "Fort Smith",
        "Fayetteville",
        "Springdale",
        "Jonesboro",
        "North Little Rock",
        "Conway",
        "Rogers",
        "Pine Bluff",
        "Bentonville",
    ],
    "Utah": [
        "Salt Lake City",
        "West Valley City",
        "Provo",
        "West Jordan",
        "Orem",
        "Sandy",
        "Ogden",
        "St. George",
        "Layton",
        "Taylorsville",
        "South Jordan",
        "Lehi",
        "Logan",
        "Murray",
        "Draper",
        "Bountiful",
        "Riverton",
        "Roy",
    ],
    "Rhode Island": [
        "Providence",
        "Warwick",
        "Cranston",
        "Pawtucket",
        "East Providence",
        "Woonsocket",
    ],
    "Mississippi": [
        "Jackson",
        "Gulfport",
        "Southaven",
        "Hattiesburg",
        "Biloxi",
        "Meridian",
    ],
    "South Dakota": ["Sioux Falls", "Rapid City"],
    "Connecticut": [
        "Bridgeport",
        "New Haven",
        "Stamford",
        "Hartford",
        "Waterbury",
        "Norwalk",
        "Danbury",
        "New Britain",
        "Meriden",
        "Bristol",
        "West Haven",
        "Milford",
        "Middletown",
        "Norwich",
        "Shelton",
    ],
    "South Carolina": [
        "Columbia",
        "Charleston",
        "North Charleston",
        "Mount Pleasant",
        "Rock Hill",
        "Greenville",
        "Summerville",
        "Sumter",
        "Goose Creek",
        "Hilton Head Island",
        "Florence",
        "Spartanburg",
    ],
    "New Hampshire": ["Manchester", "Nashua", "Concord"],
    "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot"],
    "Montana": ["Billings", "Missoula", "Great Falls", "Bozeman"],
    "Delaware": ["Wilmington", "Dover"],
    "Maine": ["Portland"],
    "Wyoming": ["Cheyenne", "Casper"],
    "West Virginia": ["Charleston", "Huntington"],
    "Vermont": ["Burlington"],
}
Drugs = [
    {"Generic Name": "alendronate tablet", "Brand Name": "Fosamax"},
    {"Generic Name": "acyclovir capsule", "Brand Name": "Zovirax"},
    {"Generic Name": "acyclovir tablet", "Brand Name": "Zovirax"},
    {
        "Generic Name": "albuterol inhalation solution",
        "Brand Name": "Albuterol Inhalation Solution",
    },
    {
        "Generic Name": "albuterol sulfate",
        "Brand Name": "ProAir RespiClick Powder Inhaler",
    },
    {"Generic Name": "alclometasone dipropionate cream", "Brand Name": "Aclovate"},
    {"Generic Name": "alfuzosin hcl", "Brand Name": "Uroxatral"},
    {"Generic Name": "alitretinoin", "Brand Name": "Panretin gel"},
    {"Generic Name": "allopurinol tablet", "Brand Name": "Zyloprim"},
    {"Generic Name": "alprazolam", "Brand Name": "Xanax"},
    {"Generic Name": "altretamine", "Brand Name": "Hexalen capsules"},
    {"Generic Name": "amiodarone tablet", "Brand Name": "Cordarone"},
    {"Generic Name": "amitriptyline tablet", "Brand Name": "Elavil"},
    {"Generic Name": "amlodipine and valsartan", "Brand Name": "Exforge"},
    {"Generic Name": "amlodipine besylate", "Brand Name": "Norvasc"},
    {
        "Generic Name": "amlodipine, valsartan, hydrochlorothiazide",
        "Brand Name": "Exforge HCT",
    },
    {"Generic Name": "Amlodipine/Benazepril capsule", "Brand Name": "Lotrel"},
    {"Generic Name": "amoxapine tablet", "Brand Name": "Amoxapine tablet"},
    {"Generic Name": "anastrazole", "Brand Name": "Arimidex"},
    {"Generic Name": "antihypertensive combinations", "Brand Name": "Hyzaar"},
    {
        "Generic Name": "artificial tears 1.4% drops (OTC)",
        "Brand Name": "Artificial Tears 1.4% drops (OTC)",
    },
    {
        "Generic Name": "aspirin EC tablet (OTC)",
        "Brand Name": "Aspirin EC Tablet (OTC)",
    },
    {"Generic Name": "atenolol tablet", "Brand Name": "Tenormin"},
    {"Generic Name": "atenolol/chlorthalidone tablet", "Brand Name": "Tenoretic"},
    {"Generic Name": "atorvastatin calcium", "Brand Name": "Lipitor"},
    {
        "Generic Name": "augmented betamethasone dipropionate",
        "Brand Name": "Diprolene Cream",
    },
    {"Generic Name": "azathioprine", "Brand Name": "Imuran"},
    {"Generic Name": "azelastine", "Brand Name": "Astepro"},
    {"Generic Name": "Azelastine nasal spray", "Brand Name": "Astelin"},
    {"Generic Name": "baclofen tablet", "Brand Name": "Lioresal"},
    {
        "Generic Name": "Belladonna Alkaloids with Phenobarbital",
        "Brand Name": "Donnatal Tablet",
    },
    {"Generic Name": "benazepril HCTZ tablet", "Brand Name": "Lotensin HCT"},
    {"Generic Name": "benazepril tablet", "Brand Name": "Lotensin"},
    {"Generic Name": "benzonatate", "Brand Name": "Tessalon Capsule"},
    {"Generic Name": "benzonatate capsule", "Brand Name": "Benzonatate capsule"},
    {"Generic Name": "benztropine tablet", "Brand Name": "Benztropine tablet"},
    {"Generic Name": "bethanechol tablet", "Brand Name": "Urecholine"},
    {"Generic Name": "bicalutamide", "Brand Name": "Casodex"},
    {"Generic Name": "bisoprolol/HCTZ tablet", "Brand Name": "Ziac"},
    {
        "Generic Name": "brimonidine tartrate",
        "Brand Name": "Brimonidine Tartrate 0.2% Solution",
    },
    {"Generic Name": "bromocriptine tablet", "Brand Name": "Bromocriptine tablet"},
    {
        "Generic Name": "budesonide inhalation suspension",
        "Brand Name": "Pulmicort Respules",
    },
    {"Generic Name": "bupropion hcl", "Brand Name": "Wellbutrin SR"},
    {"Generic Name": "bupropion hcl", "Brand Name": "Wellbutrin XL"},
    {"Generic Name": "bupropion HCL tablet", "Brand Name": "Wellbutrin"},
    {"Generic Name": "buspirone tablet", "Brand Name": "Buspar"},
    {
        "Generic Name": "Calcitonin-salmon (rDNA origin)",
        "Brand Name": "Fortical Nasal Spray",
    },
    {"Generic Name": "calcitriol capsule", "Brand Name": "Rocaltrol"},
    {"Generic Name": "calcium acetate", "Brand Name": "PhosLo gelcaps"},
    {
        "Generic Name": "candesartan cilexetil-hydrochlorothiazide",
        "Brand Name": "Atacand HCT",
    },
    {"Generic Name": "candesartan cilextil", "Brand Name": "Atacand"},
    {
        "Generic Name": "capsaicin cream, 0.035% (OTC)",
        "Brand Name": "Capsaicin Cream, 0.035% (OTC)",
    },
    {"Generic Name": "captopril tablet", "Brand Name": "Capoten"},
    {"Generic Name": "carbamazepine tablet", "Brand Name": "Tegretol"},
    {"Generic Name": "carbidopa/levo SR tablet", "Brand Name": "Sinemet CR"},
    {"Generic Name": "carbidopa/levo tablet", "Brand Name": "Sinemet"},
    {"Generic Name": "carvedilol", "Brand Name": "Coreg tablets"},
    {"Generic Name": "cetirizine HCl tablet - OTC", "Brand Name": "Zyrtec OTC"},
    {"Generic Name": "cevimeline HCl", "Brand Name": "Evoxac"},
    {
        "Generic Name": "chlordiazepoxide capsule",
        "Brand Name": "Chlordiazepoxide capsule",
    },
    {"Generic Name": "chlorpromazine HCL", "Brand Name": "Chlorpromazine HCL"},
    {"Generic Name": "chlorthalidone tablet", "Brand Name": "Chlorthalidone tablet"},
    {"Generic Name": "cholestyramine", "Brand Name": "Prevalite Powder"},
    {"Generic Name": "cilostazol tablet", "Brand Name": "Pletal"},
    {"Generic Name": "citalopram tablet", "Brand Name": "Celexa"},
    {"Generic Name": "clindamycin phosphate", "Brand Name": "Cleocin"},
    {"Generic Name": "clonazepam tablet", "Brand Name": "Klonopin"},
    {"Generic Name": "clonidine HCL tablets", "Brand Name": "Catapres"},
    {"Generic Name": "clonidine patch", "Brand Name": "Catapres TTS -3"},
    {"Generic Name": "clopidogrel bisulfate tablets", "Brand Name": "Plavix"},
    {
        "Generic Name": "clotrimazole/betamethasone cream",
        "Brand Name": "Lotrisone Cream",
    },
    {"Generic Name": "colestipol hcl", "Brand Name": "Colestid"},
    {"Generic Name": "decitabine", "Brand Name": "Dacogen"},
    {"Generic Name": "Dexmethylphenidate HCl tablet", "Brand Name": "Focalin"},
    {
        "Generic Name": "dextroamphetamine sulfate ER capsule",
        "Brand Name": "Dextroamphetamine sulfate ER capsule",
    },
    {
        "Generic Name": "dextroamphetamine-amphetamine ER capsule",
        "Brand Name": "Adderall XR",
    },
    {
        "Generic Name": "dextroamphetamine-amphetamine tablet",
        "Brand Name": "Dextroamphetamine-Amphetamine tablet",
    },
    {"Generic Name": "diazepam tablet", "Brand Name": "Valium"},
    {"Generic Name": "diclofenac EC tablet", "Brand Name": "Voltaren"},
    {"Generic Name": "diclofenac ER tablet", "Brand Name": "Voltaren XR"},
    {"Generic Name": "dicyclomine capsule", "Brand Name": "Bentyl"},
    {"Generic Name": "dicyclomine tablet", "Brand Name": "Bentyl"},
    {"Generic Name": "digoxin tablets", "Brand Name": "Lanoxin"},
    {"Generic Name": "diltiazem ER capsule", "Brand Name": "Dilacor XR"},
    {"Generic Name": "diltiazem hcl cd", "Brand Name": "Cardizem CD"},
    {
        "Generic Name": "diphenoxylate hydrochloride/atropine sulfate",
        "Brand Name": "Lomotil",
    },
    {"Generic Name": "diphenoxylate/atropine tablet", "Brand Name": "Lonox"},
    {"Generic Name": "Divalproex DR tablet", "Brand Name": "Depakote"},
    {"Generic Name": "donepezil HCI", "Brand Name": "Aricept"},
    {"Generic Name": "dorzolamide HCL", "Brand Name": "Trusopt"},
    {"Generic Name": "doxazosin mesylate", "Brand Name": "Cardura"},
    {"Generic Name": "doxepin capsule", "Brand Name": "Doxepin capsule"},
    {"Generic Name": "enalapril maleate tablet", "Brand Name": "Vasotec"},
    {
        "Generic Name": "enalapril maleate-hydrochlorothiazide tablets",
        "Brand Name": "Vaseretic",
    },
    {
        "Generic Name": "epinephrine auto injector",
        "Brand Name": "Epinephrine Auto Injector .3mg",
    },
    {"Generic Name": "eplerenone tablet", "Brand Name": "Eplerenone tablet"},
    {"Generic Name": "escitalopram oxalate", "Brand Name": "Lexapro"},
    {"Generic Name": "escitalopram oxalate", "Brand Name": "Lexapro 20mg"},
    {"Generic Name": "escitalopram oxalate", "Brand Name": "Lexapro 5mg"},
    {"Generic Name": "esomeprazole DR capsule", "Brand Name": "Nexium"},
    {"Generic Name": "estradiol tablet", "Brand Name": "Estrace"},
    {"Generic Name": "estropipate tablet", "Brand Name": "Ogen"},
    {"Generic Name": "eszopiclone", "Brand Name": "Lunesta"},
    {"Generic Name": "etodolac capsule", "Brand Name": "Lodine"},
    {"Generic Name": "etodolac tablet", "Brand Name": "Lodine tablet"},
    {"Generic Name": "famotidine tablet", "Brand Name": "Pepcid"},
    {"Generic Name": "felodipine ER tablet", "Brand Name": "Plendil ER"},
    {"Generic Name": "fenofibrate", "Brand Name": "Tricor"},
    {"Generic Name": "fenofibrate, micronized capsule", "Brand Name": "Lofibra"},
    {"Generic Name": "fenofibric acid DR capsule", "Brand Name": "Trilipix"},
    {
        "Generic Name": "ferrous sulfate EC tablet",
        "Brand Name": "Ferrous Sulfate EC tablet",
    },
    {"Generic Name": "finasteride tablet", "Brand Name": "Proscar"},
    {
        "Generic Name": "flecainide acetate tablet",
        "Brand Name": "Flecainide Acetate tablet",
    },
    {"Generic Name": "fluconazole", "Brand Name": "Diflucan"},
    {"Generic Name": "fluoxetine capsule", "Brand Name": "Prozac"},
    {
        "Generic Name": "fluticasone nasal spray (50 mcg)",
        "Brand Name": "Flonase (50 mcg)",
    },
    {
        "Generic Name": "fluvoxamine maleate tablet",
        "Brand Name": "Fluvoxamine Maleate tablet",
    },
    {"Generic Name": "folic acid 2.2 tablet", "Brand Name": "Folic Acid 2.2 tablet"},
    {"Generic Name": "folic acid tablet", "Brand Name": "Folic Acid"},
    {"Generic Name": "furosemide tablet", "Brand Name": "Lasix"},
    {"Generic Name": "gabapentin", "Brand Name": "Neurontin"},
    {"Generic Name": "gemfibrozil", "Brand Name": "Lopid"},
    {"Generic Name": "glimepiride", "Brand Name": "Amaryl"},
    {"Generic Name": "glipizide", "Brand Name": "Glucotrol"},
    {"Generic Name": "glipizide extended release", "Brand Name": "Glucotrol XL"},
    {"Generic Name": "glyburide tablet", "Brand Name": "Micronase"},
    {"Generic Name": "glyburide/Metformin tablet", "Brand Name": "Glucovance"},
    {"Generic Name": "guanfacine", "Brand Name": "Intuniv Extended Release Tablets"},
    {"Generic Name": "halobetasol prop ointment, 0.05%", "Brand Name": "Ultravate"},
    {"Generic Name": "haloperidol tablet", "Brand Name": "Haloperidol tablet"},
    {"Generic Name": "hydralazine tablet", "Brand Name": "Hydralazine tablet"},
    {"Generic Name": "hydrochlorothiazide capsule", "Brand Name": "Microzide"},
    {
        "Generic Name": "hydrochlorothiazide tablet",
        "Brand Name": "hydrochlorothiazide tablet",
    },
    {"Generic Name": "hydrocortisone tablet", "Brand Name": "Hydrocortisone tablet"},
    {"Generic Name": "hydroxychloroquine tablet", "Brand Name": "Plaquenil"},
    {"Generic Name": "hydroxyurea capsule", "Brand Name": "Hydrea"},
    {"Generic Name": "hydroxyzine HCL tablet", "Brand Name": "Hydroxyzine HCL tablet"},
    {"Generic Name": "hydroxyzine pamoate", "Brand Name": "Vistaril"},
    {"Generic Name": "ibuprofen tablet", "Brand Name": "Motrin"},
    {"Generic Name": "indapamide tablet", "Brand Name": "Indapamide tablet"},
    {
        "Generic Name": "Ipratropium/Albuterol Inhalation Solution",
        "Brand Name": "DuoNeb",
    },
    {"Generic Name": "irbesartan", "Brand Name": "Avapro"},
    {"Generic Name": "irbesartan-hydrochlorothiazide", "Brand Name": "Avalide"},
    {"Generic Name": "isoniazid tablet", "Brand Name": "Isoniazid/INH"},
    {"Generic Name": "isosorbide mononitrate", "Brand Name": "Imdur"},
    {"Generic Name": "isosorbide mononitrate (10mg,20mg)", "Brand Name": "Ismo"},
    {"Generic Name": "isosorbide mononitrate (10mg,20mg)", "Brand Name": "Monoket"},
    {"Generic Name": "ketotifen fumerate OTC solution", "Brand Name": "Alaway OTC"},
    {"Generic Name": "labetalol HCL tablet", "Brand Name": "Trandate"},
    {"Generic Name": "lactulose oral solution", "Brand Name": "Enulose"},
    {"Generic Name": "lamotrigine", "Brand Name": "Lamictal"},
    {"Generic Name": "lansoprazole DR capsule", "Brand Name": "Prevacid"},
    {"Generic Name": "latanoprost solution", "Brand Name": "Xalatan"},
    {"Generic Name": "letrozole", "Brand Name": "Femara"},
    {"Generic Name": "levalbuterol hcl", "Brand Name": "Xopenex"},
    {"Generic Name": "levetiracetam ER", "Brand Name": "Keppra XR tablets"},
    {"Generic Name": "levetiracetam tablet", "Brand Name": "Keppra"},
    {"Generic Name": "levocetirizine dihydrochloride", "Brand Name": "Xyzal tablets"},
    {"Generic Name": "levothyroxine", "Brand Name": "Levoxyl"},
    {"Generic Name": "levothyroxine", "Brand Name": "Synthroid"},
    {
        "Generic Name": "lidocaine 2% viscous solution",
        "Brand Name": "Lidocaine 2% viscous solution",
    },
    {"Generic Name": "lidocaine patch 5%", "Brand Name": "Lidoderm"},
    {"Generic Name": "liothyronine sodium", "Brand Name": "Cytomel"},
    {"Generic Name": "lisinopril tablet", "Brand Name": "Prinivil"},
    {"Generic Name": "lisinopril tablet", "Brand Name": "Zestril"},
    {"Generic Name": "lisinopril/HCTZ tablet", "Brand Name": "Prinzide"},
    {"Generic Name": "lisinopril/HCTZ tablet", "Brand Name": "Zestoretic"},
    {"Generic Name": "Lithium Carbonate capsule", "Brand Name": "Lithium Carbonate"},
    {"Generic Name": "loperamide capsule", "Brand Name": "Loperamide capsule"},
    {"Generic Name": "loratadine OTC tablet", "Brand Name": "Claritin OTC"},
    {"Generic Name": "lorazepam tablet", "Brand Name": "Ativan"},
    {"Generic Name": "losartan potassium", "Brand Name": "Cozaar"},
    {"Generic Name": "lovastatin tablet", "Brand Name": "Mevacor"},
    {"Generic Name": "loxapine capsule", "Brand Name": "Loxapine capsule"},
    {
        "Generic Name": "magnesium oxide tablet (OTC)",
        "Brand Name": "Magnesium Oxide tablet (OTC)",
    },
    {"Generic Name": "meclizine HCI", "Brand Name": "Antivert"},
    {"Generic Name": "medroxyprogesterone acetate", "Brand Name": "Provera"},
    {"Generic Name": "meloxicam", "Brand Name": "Mobic"},
    {"Generic Name": "memantine hcl", "Brand Name": "Namenda"},
    {"Generic Name": "metformin", "Brand Name": "Glucophage"},
    {"Generic Name": "metformin hcl, extended release", "Brand Name": "Glucophage XR"},
    {"Generic Name": "methimazole tablets", "Brand Name": "Tapazole"},
    {"Generic Name": "methocarbamol tablet", "Brand Name": "Robaxin"},
    {"Generic Name": "methotrexate", "Brand Name": "Methotrexate"},
    {"Generic Name": "methylphenidate CD capsule", "Brand Name": "Metadate CD"},
    {"Generic Name": "methylphenidate hcl", "Brand Name": "Ritalin LA"},
    {"Generic Name": "methylphenidate tablet", "Brand Name": "Ritalin"},
    {"Generic Name": "metoclopramide HCL tablet", "Brand Name": "Reglan"},
    {"Generic Name": "metolazone tablet", "Brand Name": "Zaroxolyn"},
    {"Generic Name": "metoprolol succinate/hctz", "Brand Name": "Dutoprol Tablet"},
    {"Generic Name": "metoprolol tartrate tablet", "Brand Name": "Lopressor"},
    {"Generic Name": "micronized glyburide", "Brand Name": "Glynase PresTab"},
    {"Generic Name": "midodrine HCl tablet", "Brand Name": "Midodrine HCl tablet"},
    {"Generic Name": "minocycline capsule", "Brand Name": "Minocin"},
    {"Generic Name": "minocycline HCL capsule", "Brand Name": "Dynacin"},
    {"Generic Name": "mirtazapine tablet", "Brand Name": "Remeron"},
    {"Generic Name": "mometasone furoate", "Brand Name": "Elocon Cream"},
    {"Generic Name": "mometasone furoate", "Brand Name": "Elocon Ointment"},
    {"Generic Name": "montelukast sodium", "Brand Name": "Singulair"},
    {"Generic Name": "mycophenolate mofetil", "Brand Name": "CellCept"},
    {"Generic Name": "nabumetone tablet", "Brand Name": "Nabumetone tablet"},
    {"Generic Name": "naproxen sodium tablet", "Brand Name": "Anaprox DS"},
    {"Generic Name": "naproxen tablet", "Brand Name": "Naprosyn"},
    {"Generic Name": "niacin", "Brand Name": "Niacin"},
    {"Generic Name": "niacin extented-release tablets", "Brand Name": "Niaspan ER"},
    {
        "Generic Name": "niacin SA capsule (OTC)",
        "Brand Name": "Niacin SA capsule (OTC)",
    },
    {"Generic Name": "nifedipine capsule", "Brand Name": "Nifedipine capsule"},
    {"Generic Name": "nifedipine CR tablet", "Brand Name": "Adalat cc"},
    {"Generic Name": "nilutamide", "Brand Name": "Nilandron tablet"},
    {
        "Generic Name": "nitroglycerin SA capsule",
        "Brand Name": "Nitroglycerin SA capsule",
    },
    {"Generic Name": "norethindrone tablet", "Brand Name": "Ortho Micronor"},
    {
        "Generic Name": "norethindrone/ethinyl estradiol tablet",
        "Brand Name": "Ovcon 35",
    },
    {"Generic Name": "nortriptyline HCL capsule", "Brand Name": "Pamelor"},
    {"Generic Name": "nyamyc topical powder", "Brand Name": "Nystatin powder"},
    {"Generic Name": "nystatin tablet", "Brand Name": "Nystatin tablet"},
    {"Generic Name": "olanzapine", "Brand Name": "Zyprexa"},
    {"Generic Name": "omega-3-acid ethyl esters", "Brand Name": "Lovaza"},
    {"Generic Name": "omeprazole capsule", "Brand Name": "Prilosec"},
    {"Generic Name": "ondansetron ODT tablet", "Brand Name": "Zofran ODT"},
    {"Generic Name": "ondansetron tablet", "Brand Name": "Zofran"},
    {"Generic Name": "oxandrolone tablet", "Brand Name": "Oxandrin"},
    {"Generic Name": "oxybutynin tablet", "Brand Name": "Ditropan"},
    {"Generic Name": "pantoprazole sodium", "Brand Name": "Protonix"},
    {"Generic Name": "paroxetine HCL tablet", "Brand Name": "Paxil"},
    {"Generic Name": "pentoxifylline ER tablet", "Brand Name": "Trental"},
    {"Generic Name": "perphenazine tablet", "Brand Name": "Perphenazine tablet"},
    {
        "Generic Name": "Phenobarbital, Hyoscyamine Sulfate, Atropine Sulfate, Scopolamine Hydrobromide",
        "Brand Name": "Donnatal Elixir",
    },
    {"Generic Name": "phenoxybenzamine", "Brand Name": "Dibenzyline capsule"},
    {"Generic Name": "phenytoin sodium capsule", "Brand Name": "Dilantin"},
    {"Generic Name": "pilocarpine", "Brand Name": "Salagen Tablet"},
    {"Generic Name": "pioglitazone hydrochloride", "Brand Name": "Actos"},
    {
        "Generic Name": "PNV Prenatal Multivitamin Plus Iron",
        "Brand Name": "PNV Prenatal Multivitamin Plus Iron",
    },
    {"Generic Name": "potassium chloride ER tablet", "Brand Name": "K-Dur 20MEQ"},
    {"Generic Name": "potassium chloride ER tablet", "Brand Name": "Klor-Con 10mEQ"},
    {"Generic Name": "potassium chloride ER tablet", "Brand Name": "Klor-Con M20"},
    {"Generic Name": "potassium Iodide", "Brand Name": "SSKI oral solution"},
    {
        "Generic Name": "pramipexole dihydrochloride tablets",
        "Brand Name": "Mirapex tablets",
    },
    {"Generic Name": "pravastatin tablet", "Brand Name": "Pravachol"},
    {"Generic Name": "prazosin capsule", "Brand Name": "prazosin capsule"},
    {"Generic Name": "prednisone tablet", "Brand Name": "Prednisone tablet"},
    {"Generic Name": "primidone", "Brand Name": "Mysoline"},
    {
        "Generic Name": "prochlorperazine tablet",
        "Brand Name": "Prochlorperazine tablet",
    },
    {"Generic Name": "progesterone capsule", "Brand Name": "Progesterone capsule"},
    {"Generic Name": "propafenone hydrochloride", "Brand Name": "Rythmol"},
    {"Generic Name": "propranolol HCL ER", "Brand Name": "Inderal LA Capsules"},
    {"Generic Name": "propranolol tablet", "Brand Name": "Inderal"},
    {
        "Generic Name": "propylthiouracil tablet",
        "Brand Name": "Propylthiouracil tablet",
    },
    {"Generic Name": "pyridostigmine bromide", "Brand Name": "Mestinon"},
    {"Generic Name": "quetiapine fumarate", "Brand Name": "Seroquel"},
    {"Generic Name": "quinapril HCI", "Brand Name": "Accupril"},
    {"Generic Name": "quinapril/HCTZ tablet", "Brand Name": "Accuretic"},
    {"Generic Name": "rabeprazole sodium", "Brand Name": "Aciphex"},
    {"Generic Name": "raloxifene tablet", "Brand Name": "Evista"},
    {"Generic Name": "ramipril", "Brand Name": "Altace"},
    {"Generic Name": "ranolazine extended-release tablets", "Brand Name": "Ranexa"},
    {"Generic Name": "rasagiline tablets", "Brand Name": "Azilect"},
    {"Generic Name": "repaglinide tablet", "Brand Name": "Prandin"},
    {"Generic Name": "risedronate sodium tablet", "Brand Name": "Actonel"},
    {"Generic Name": "risperidone", "Brand Name": "Risperdal"},
    {"Generic Name": "rivastigmine tartrate capsule", "Brand Name": "Exelon"},
    {"Generic Name": "ropinirole hydrochloride", "Brand Name": "Requip tablets"},
    {"Generic Name": "rosuvastatin calcium", "Brand Name": "Crestor"},
    {"Generic Name": "rufinamide", "Brand Name": "Banzel"},
    {"Generic Name": "rufinamide", "Brand Name": "Banzel Oral Suspension 40mg/ml"},
    {"Generic Name": "sertraline HCI", "Brand Name": "Zoloft"},
    {"Generic Name": "sildenafil citrate tablet", "Brand Name": "Revatio"},
    {"Generic Name": "sildenefil citrate", "Brand Name": "Viagra"},
    {"Generic Name": "simvastatin tablets", "Brand Name": "Zocor"},
    {"Generic Name": "spironolactone", "Brand Name": "Aldactone"},
    {
        "Generic Name": "spironolactone and hydrochlorothiazide",
        "Brand Name": "Aldactazide",
    },
    {"Generic Name": "sprintec tablet", "Brand Name": "Ortho-Cyclen"},
    {"Generic Name": "SSKI oral solution", "Brand Name": "Potassium Iodide"},
    {"Generic Name": "sucralfate", "Brand Name": "Carafate"},
    {
        "Generic Name": "sulfamethoxazole/trimethoprim DS tablet",
        "Brand Name": "Bactrim DS",
    },
    {
        "Generic Name": "sulfamethoxazole/trimethoprim DS tablet",
        "Brand Name": "Septra DS",
    },
    {"Generic Name": "sulfasalazine", "Brand Name": "Azulfidine"},
    {"Generic Name": "sulfasalazine, USP", "Brand Name": "Azulfidine EN-Tabs"},
    {"Generic Name": "sumatriptan succinate", "Brand Name": "Imitrex (Tablets)"},
    {"Generic Name": "tacrolimus capsule", "Brand Name": "Prograf"},
    {
        "Generic Name": "tamoxifen citrate tablet",
        "Brand Name": "Tamoxifen citrate tablet",
    },
    {"Generic Name": "tamsulosin hydrochloride", "Brand Name": "Flomax"},
    {"Generic Name": "telmisartan", "Brand Name": "Micardis"},
    {"Generic Name": "temazepam capsule", "Brand Name": "Restoril"},
    {"Generic Name": "terazosin capsule", "Brand Name": "Hytrin"},
    {"Generic Name": "testosterone cypionate", "Brand Name": "Depo-Testosterone"},
    {"Generic Name": "testosterone gel", "Brand Name": "AndroGel"},
    {"Generic Name": "testosterone gel packet", "Brand Name": "Vogelxo gel packet"},
    {"Generic Name": "testosterone gel pump", "Brand Name": "Vogelxo gel pump"},
    {"Generic Name": "testosterone gel tube", "Brand Name": "Vogelxo gel tube"},
    {"Generic Name": "Tizanidine 4mg tab", "Brand Name": "Zanaflex"},
    {"Generic Name": "tolterodine tartrate tablet", "Brand Name": "Detrol"},
    {"Generic Name": "topiramate", "Brand Name": "Topamax tablets"},
    {"Generic Name": "topiramate ER", "Brand Name": "Qudexy XR capsule"},
    {
        "Generic Name": "tramadol hydrochloride/acetaminophen tablets",
        "Brand Name": "Ultracet",
    },
    {"Generic Name": "tramadol tablet", "Brand Name": "Ultram"},
    {"Generic Name": "trandolapril tablet", "Brand Name": "Mavik"},
    {"Generic Name": "tranylcypromine", "Brand Name": "Parnate 10mg tablets"},
    {"Generic Name": "trazodone tablet", "Brand Name": "Desyrel"},
    {"Generic Name": "tri-previfem tablet", "Brand Name": "Ortho-Tri-Cyclen"},
    {"Generic Name": "tri-sprintec tablet", "Brand Name": "Ortho-Tri-Cyclen"},
    {
        "Generic Name": "triamcinolone cream, 0.1%",
        "Brand Name": "Triamcinolone cream, 0.1%",
    },
    {
        "Generic Name": "triamcinolone ointment, 0.1%",
        "Brand Name": "Triamcinolone ointment, 0.1%",
    },
    {"Generic Name": "triamterene", "Brand Name": "Dyrenium capsule"},
    {"Generic Name": "triamterene/HCTZ capsule", "Brand Name": "Dyazide"},
    {"Generic Name": "triamterene/HCTZ tablet", "Brand Name": "Maxzide"},
    {
        "Generic Name": "trifluoperazine HCl tablet",
        "Brand Name": "Trifluoperazine HCl tablet",
    },
    {
        "Generic Name": "trospium chloride tablet",
        "Brand Name": "Trospium Chloride tablet",
    },
    {"Generic Name": "valacyclovir HCL tablet", "Brand Name": "Valtrex tablet"},
    {"Generic Name": "valproic acid", "Brand Name": "Depakene"},
    {"Generic Name": "valsartan hydrochloride", "Brand Name": "Diovan"},
    {"Generic Name": "valsartan hydrochlorothiazide", "Brand Name": "Diovan HCT"},
    {"Generic Name": "venlafaxine tablet", "Brand Name": "Effexor"},
    {"Generic Name": "verapamil HCl", "Brand Name": "Calan"},
    {"Generic Name": "verapamil SR tablet", "Brand Name": "Calan-SR"},
    {"Generic Name": "verapamil SR tablet", "Brand Name": "Isoptin-SR"},
    {
        "Generic Name": "Vitamin B Complex capsule (OTC)",
        "Brand Name": "Vitamin B Complex capsule (OTC)",
    },
    {
        "Generic Name": "Vitamin B-6 tablet (OTC)",
        "Brand Name": "Vitamin B-6 tablet (OTC)",
    },
    {
        "Generic Name": "Vitamin D3 capsule (OTC)",
        "Brand Name": "Vitamin D3 capsule (OTC)",
    },
    {
        "Generic Name": "Vitamin D3 tablet (OTC)",
        "Brand Name": "Vitamin D3 tablet (OTC)",
    },
    {"Generic Name": "warfarin sodium", "Brand Name": "Jantoven"},
    {"Generic Name": "zafirlukast", "Brand Name": "Accolate"},
    {"Generic Name": "zaleplon", "Brand Name": "Sonata"},
    {"Generic Name": "zidovudine tablet", "Brand Name": "Zidovudine tablet"},
    {"Generic Name": "Zolpidem", "Brand Name": "Ambien"},
]

DRUGS_PAYLOAD = []
for drug in Drugs:
    drug.update({"Price": round(float(np.random.normal(50.0, 25.0, (1, 1))[0]), 2)})
    DRUGS_PAYLOAD.append(drug)
